export type { IProduct, INutrition } from "./model/types"
export { useProductModel } from "./model"
export { mappedProducts } from "./lib"
export { ProductCard, SkeletonProductCard } from "./ui"
export * as ProductApi from "./api"
