export type { IProduct, INutrition } from "./model/types"
export { useProductModel } from "./model"
export { mappedProducts } from "./lib"
export { ProductCard, SkeletonCard } from "./ui"
export * as ProductApi from "./api"
